<?php
session_start();
require_once 'includes/auth.php';
require_once 'includes/config.php';
require_once 'includes/layout.php';
requireLogin();

$msg = ''; $err = '';
$accounts = readAccounts();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    if ($action === 'save') {
        $content = $_POST['config_content'] ?? '';
        if (writeConfig($content)) {
            $msg = 'config.lua saved successfully.';
        } else {
            $err = 'Failed to write config.lua — check file permissions.';
        }
    } elseif ($action === 'generate') {
        // Auto-generate config.lua from accounts + rules
        $rules    = readRules();
        $lua = "-- Auto-generated by IMAPFilter Web UI\n";
        $lua .= "-- " . date('Y-m-d H:i:s') . "\n\n";
        $lua .= "options.timeout = 120\noptions.subscribe = true\n\n";
        foreach ($accounts as $acc) {
            $n = $acc['name'];
            $lua .= "{$n} = IMAP {\n";
            $lua .= "  server   = '{$acc['host']}',\n";
            $lua .= "  port     = " . ($acc['port'] ?? 993) . ",\n";
            $lua .= "  username = '{$acc['username']}',\n";
            $lua .= "  password = '{$acc['password']}',\n";
            $lua .= "  ssl      = '" . (!empty($acc['tls']) ? 'ssl3' : 'none') . "',\n";
            $lua .= "}\n\n";
        }
        foreach ($rules as $r) {
            if (empty($r['enabled'])) continue;
            $lua .= "-- Rule: {$r['name']}\n";
            $mailbox = $r['mailbox'] ?? 'INBOX';
            $lua .= "msgs = {$r['account']}['{$mailbox}']";
            $crit = $r['criteria'] ?? 'from';
            $val  = addslashes($r['criteria_val'] ?? '');
            switch ($crit) {
                case 'from':    $lua .= ":contain_from('{$val}')"; break;
                case 'to':      $lua .= ":contain_to('{$val}')"; break;
                case 'subject': $lua .= ":contain_subject('{$val}')"; break;
                case 'cc':      $lua .= ":contain_cc('{$val}')"; break;
                case 'body':    $lua .= ":contain_body('{$val}')"; break;
                case 'seen':    $lua .= ":is_seen()"; break;
                case 'unseen':  $lua .= ":is_unseen()"; break;
                case 'flagged': $lua .= ":is_flagged()"; break;
                case 'older':   $lua .= ":is_older({$val})"; break;
            }
            $lua .= "\n";
            switch ($r['action']) {
                case 'move':     $lua .= "msgs:move_messages({$r['account']}['" . addslashes($r['target'] ?? '') . "'])\n"; break;
                case 'copy':     $lua .= "msgs:copy_messages({$r['account']}['" . addslashes($r['target'] ?? '') . "'])\n"; break;
                case 'delete':   $lua .= "msgs:delete_messages()\n"; break;
                case 'flag':     $lua .= "msgs:flag_messages()\n"; break;
                case 'mark_seen':$lua .= "msgs:mark_seen()\n"; break;
            }
            $lua .= "\n";
        }
        if (writeConfig($lua)) {
            $msg = 'config.lua generated and saved.';
        } else {
            $err = 'Failed to write config.lua.';
        }
    }
}

$configContent = readConfig();
pageHeader('CONFIG.LUA', 'config');
?>

<?php if ($msg): ?><div class="alert alert-ok"><?= $msg ?></div><?php endif; ?>
<?php if ($err): ?><div class="alert alert-error"><?= $err ?></div><?php endif; ?>

<div class="config-toolbar">
  <form method="POST" style="display:inline">
    <input type="hidden" name="action" value="generate">
    <button type="submit" class="btn-action" onclick="return confirm('Overwrite config.lua with auto-generated content?')">
      ⚙ AUTO-GENERATE FROM ACCOUNTS &amp; RULES
    </button>
  </form>
  <span class="config-path">PATH: <?= htmlspecialchars(IMAPFILTER_CONFIG) ?></span>
</div>

<div class="panel">
  <div class="panel-header">◉ EDIT config.lua</div>
  <div class="panel-body no-pad">
    <form method="POST">
      <input type="hidden" name="action" value="save">
      <div class="editor-wrap">
        <div class="editor-gutter" id="gutter"></div>
        <textarea name="config_content" id="lua-editor" class="lua-editor" spellcheck="false"><?= htmlspecialchars($configContent) ?></textarea>
      </div>
      <div class="editor-actions">
        <button type="submit" class="btn-primary">💾 SAVE CONFIG.LUA</button>
        <span class="editor-hint">Ctrl+S to save · Lua syntax</span>
      </div>
    </form>
  </div>
</div>

<script>
// Simple line gutter
const editor = document.getElementById('lua-editor');
const gutter = document.getElementById('gutter');
function updateGutter() {
  const lines = editor.value.split('\n').length;
  gutter.innerHTML = Array.from({length: lines}, (_, i) => `<span>${i+1}</span>`).join('');
}
editor.addEventListener('input', updateGutter);
editor.addEventListener('scroll', () => { gutter.scrollTop = editor.scrollTop; });
updateGutter();

// Tab support
editor.addEventListener('keydown', e => {
  if (e.key === 'Tab') {
    e.preventDefault();
    const s = editor.selectionStart, end = editor.selectionEnd;
    editor.value = editor.value.substring(0, s) + '  ' + editor.value.substring(end);
    editor.selectionStart = editor.selectionEnd = s + 2;
  }
  if (e.ctrlKey && e.key === 's') {
    e.preventDefault();
    editor.closest('form').submit();
  }
});
</script>

<?php pageFooter(); ?>
